current_dir := ${CURDIR}
TOP := full_cpu_timing_top
SOURCES := ${current_dir}/full_cpu.v ${current_dir}/full_cpu_timing_top.v
XDC := ${current_dir}/arty_a7_100t.xdc
TARGET := arty_100

include ../../.tools/f4pga-examples/common/common.mk
