current_dir := ${CURDIR}
TOP := block_transfer_timing_top
SOURCES := $(CURDIR)/block_transfer_control.v $(CURDIR)/block_transfer_timing_top.v
XDC := $(CURDIR)/arty_a7_100t.xdc
TARGET := arty_100

include ../../.tools/f4pga-examples/common/common.mk
